# SPDX-License-Identifier: MIT-0
---

- name: Check Node BMC Status
  ansible.builtin.include_tasks: tasks/status_bmc.yml
  vars:
    bmc: "{{ hostvars[inventory_hostname]['bmc'] }}"
    slot: "{{ hostvars[inventory_hostname]['slot'] }}"
    node: "{{ inventory_hostname }}"
