# SPDX-License-Identifier: MIT-0
---

- name: Flash Nodes
  when: >
    inventory_hostname in groups['nodes'] and
    inventory_hostname == hostvars[node].inventory_hostname and
    ansible_limit | default('nodes,!tpi')
  ansible.builtin.include_tasks: tasks/status_bmc.yml
  with_items: "{{ groups['nodes'] }}"
  loop_control:
    loop_var: node
