# SPDX-License-Identifier: MIT-0
---

- name: Flash Nodes
  when: >
    inventory_hostname in groups['nodes'] and
    ansible_limit | default('nodes,!tpi')
  block:
    - name: Check Node BMC Status
      ansible.builtin.include_tasks: tasks/status_bmc.yml
