# SPDX-License-Identifier: MIT-0
#
# Check node status
- name: Check BMC status for {{ inventory_hostname }}
  delegate_to: localhost
  ansible.builtin.wait_for:
    host: "{{ hostvars[hostvars[inventory_hostname]['bmc']]['ansible_host'] }}"
    port: 22
    timeout: 5
  failed_when: false
  register: node_check

- name: Show BMC status for {{ inventory_hostname }}
  tags: [never,debug]
  ansible.builtin.debug:
    var: node_check

- name: Set BMC status for {{ inventory_hostname }}
  ansible.builtin.set_fact:
    node_status: "{{ not node_check is search('Timeout') | bool }}"

- name: Show BMC Status for {{ inventory_hostname }}
  ansible.builtin.debug:
    var: node_status
